# Generated by Django 4.2.9 on 2024-01-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_license_alter_driver_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='sarath@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default='123456', max_length=500),
            preserve_default=False,
        ),
    ]
