# Generated by Django 4.2.9 on 2024-01-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_remove_driver_age_remove_driver_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDriver',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drivertoken', to='driver.driver')),
            ],
        ),
    ]
