# Generated by Django 4.2.9 on 2024-01-30 18:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_alter_driver_license_alter_driver_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('dropoff_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('0', 'started'), ('1', 'completed'), ('2', 'cancelled')], max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_ride', to='ride.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ride_driver', to='driver.driver')),
            ],
        ),
    ]
