# Generated by Django 4.2.9 on 2024-01-31 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCustomer',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customertoken', to='ride.customer')),
            ],
        ),
    ]
