# Generated by Django 4.2.9 on 2024-02-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_tokencustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('car_type', models.IntegerField(blank=True, null=True)),
                ('seat_capacity', models.IntegerField(blank=True, null=True)),
                ('boot_capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='accept',
            field=models.CharField(blank=True, choices=[('0', 'REJECT'), ('1', 'ACCEPT')], max_length=255, null=True),
        ),
    ]
